name: My CI

on: push

jobs:
  E2E-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'zulu'
          architecture: x64
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: cd app && npm install && cd ../
      - name: End-to-End tests with Cypress
        uses: cypress-io/github-action@v2
        with:
          config: pageLoadTimeout=100000,video=false
          start: npm run test:ci
          wait-on: "http://localhost:3000"
